const AuthType = {
    AUTH_LOGIN: "AUTH_LOGIN",
    SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
    SEND_OTP_FAIL: "SEND_OTP_FAIL",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAIL: "VERIFY_OTP_FAIL",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    SKIP_LOGIN: "SKIP_LOGIN",
    LOGOUT: "LOGOUT",
}

export default AuthType